In [1]:
()

()

In [2]:
fav=("python","julia","r")
fav

("python", "julia", "r")

In [3]:
x1=(1,2,3)
x1

(1, 2, 3)

In [4]:
x2=(1,2.0,"tmp")

(1, 2.0, "tmp")

In [5]:
x3=(a=2,b=1+2)

(a = 2, b = 3)

In [6]:
length(x2)

3

In [7]:
x2[1], x2[2]

(1, 2.0)

In [8]:
c=x1[2]+x1[3]

5

In [9]:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [10]:
in("tmp", x2), 0 in x2

(true, false)

In [11]:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), "Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [12]:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [13]:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [14]:
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [15]:
haskey(phonebook, "Иванов И.И.")

true

In [16]:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [17]:
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [18]:
phonebook

Dict{String, Any} with 2 entries:
  "Сидоров П.С." => "555-3344"
  "Бухгалтерия"  => "555-2368"

In [19]:
a=Dict("foo"=>0.0, "bar"=>42.0)
b=Dict("baz"=>17, "bar"=>13.0)
merge(a,b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

In [20]:
A=Set([1,3,4,5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [21]:
B=Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [22]:
S1=Set([1,2])
S2=Set([3,4])
issetequal(S1,S2)

false

In [23]:
s3=Set([1,2,2,3,1,2,3,2,1])
s4=Set([2,3,1])
issetequal(s3,s4)

true

In [24]:
c=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [25]:
d=intersect(S1,s3)

Set{Int64} with 2 elements:
  2
  1

In [26]:
e=setdiff(s3,S1)

Set{Int64} with 1 element:
  3

In [27]:
issubset(S1,s4)

true

In [28]:
push!(s4,99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [29]:
pop!(s4)

2

In [30]:
s4

Set{Int64} with 3 elements:
  99
  3
  1

In [31]:
ea1=[]

Any[]

In [32]:
ea2=(Integer)[]

Integer[]

In [33]:
ea3=(Float64)[]

Float64[]

In [34]:
a=[1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [35]:
b=[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [36]:
A=[[1,2,3] [4,5,6] [7,8,9]]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [37]:
B=[[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [38]:
c=rand(1,8)

1×8 Matrix{Float64}:
 0.385775  0.840777  0.814119  0.915637  …  0.121126  0.585728  0.0588356

In [39]:
C=rand(2,3)

2×3 Matrix{Float64}:
 0.143131  0.892835  0.0349428
 0.101308  0.258833  0.23488

In [40]:
D=rand(4,3,2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.167084  0.729376  0.424649
 0.546267  0.519413  0.484973
 0.571437  0.787869  0.622602
 0.841251  0.451533  0.331373

[:, :, 2] =
 0.589348  0.795452  0.415582
 0.112638  0.162374  0.290339
 0.555702  0.292073  0.0871626
 0.836485  0.283858  0.358148

In [41]:
roots=[sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [42]:
ar1=[3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [43]:
ar2=[i^2 for i in 1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

In [44]:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [45]:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [46]:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [47]:
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [48]:
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [49]:
a = collect(1:12)
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [50]:
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [51]:
c=transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [52]:
ar=rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 12  10  19  16  12
 16  18  19  12  11
 17  11  19  19  16
 17  20  17  16  19
 14  10  10  20  15
 20  11  20  15  20
 14  20  10  16  17
 14  12  12  10  16
 10  13  19  13  14
 12  11  18  11  17

In [53]:
ar[:,2]

10-element Vector{Int64}:
 10
 18
 11
 20
 10
 11
 20
 12
 13
 11

In [54]:
ar[:,[2,5]]

10×2 Matrix{Int64}:
 10  12
 18  11
 11  16
 20  19
 10  15
 11  20
 20  17
 12  16
 13  14
 11  17

In [55]:
ar[:,2:4]

10×3 Matrix{Int64}:
 10  19  16
 18  19  12
 11  19  19
 20  17  16
 10  10  20
 11  20  15
 20  10  16
 12  12  10
 13  19  13
 11  18  11

In [56]:
ar[[2,4,6],[1,5]]

3×2 Matrix{Int64}:
 16  11
 17  19
 20  20

In [57]:
ar[1,3:end]

3-element Vector{Int64}:
 19
 16
 12

In [58]:
sort(ar, dims=1)

10×5 Matrix{Int64}:
 10  10  10  10  11
 12  10  10  11  12
 12  11  12  12  14
 14  11  17  13  15
 14  11  18  15  16
 14  12  19  16  16
 16  13  19  16  17
 17  18  19  16  17
 17  20  19  19  19
 20  20  20  20  20

In [59]:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 10  12  12  16  19
 11  12  16  18  19
 11  16  17  19  19
 16  17  17  19  20
 10  10  14  15  20
 11  15  20  20  20
 10  14  16  17  20
 10  12  12  14  16
 10  13  13  14  19
 11  11  12  17  18

In [60]:
ar .> 14

10×5 BitMatrix:
 0  0  1  1  0
 1  1  1  0  0
 1  0  1  1  1
 1  1  1  1  1
 0  0  0  1  1
 1  0  1  1  1
 0  1  0  1  1
 0  0  0  0  1
 0  0  1  0  0
 0  0  1  0  1

In [61]:
findall(ar .> 14)

27-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(4, 1)
 CartesianIndex(6, 1)
 CartesianIndex(2, 2)
 CartesianIndex(4, 2)
 CartesianIndex(7, 2)
 CartesianIndex(1, 3)
 CartesianIndex(2, 3)
 CartesianIndex(3, 3)
 CartesianIndex(4, 3)
 CartesianIndex(6, 3)
 CartesianIndex(9, 3)
 ⋮
 CartesianIndex(3, 4)
 CartesianIndex(4, 4)
 CartesianIndex(5, 4)
 CartesianIndex(6, 4)
 CartesianIndex(7, 4)
 CartesianIndex(3, 5)
 CartesianIndex(4, 5)
 CartesianIndex(5, 5)
 CartesianIndex(6, 5)
 CartesianIndex(7, 5)
 CartesianIndex(8, 5)
 CartesianIndex(10, 5)

In [62]:
A=Set([0,3,4,9])
B=Set([1,3,4,7])
C=Set([0,1,2,4,7,8,9])

Set{Int64} with 7 elements:
  0
  4
  7
  2
  9
  8
  1

In [63]:
P=intersect(A,B)
P=union(P,A)
P=intersect(P,B)
P=union(P,A)
P=intersect(P,C)
P=union(P,B)
P=intersect(P,C)

Set{Int64} with 5 elements:
  0
  4
  7
  9
  1

In [64]:
t1=Set("laboratory")
t2=Set([1.0, 2.3, 4,9])
t3=Set([2,6,9])

Set{Int64} with 3 elements:
  6
  2
  9

In [65]:
issetequal(t2,t3)

false

In [66]:
union(t2,t3)

Set{Float64} with 6 elements:
  4.0
  6.0
  2.0
  2.3
  9.0
  1.0

In [67]:
union(t1,t3)

Set{Any} with 10 elements:
  6
  2
  'a'
  'l'
  'r'
  't'
  'o'
  'y'
  9
  'b'

In [68]:
pop!(t1)

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [69]:
t1

Set{Char} with 6 elements:
  'l'
  'r'
  't'
  'o'
  'y'
  'b'

In [70]:
push!(t2, 2)

Set{Float64} with 5 elements:
  4.0
  2.0
  2.3
  9.0
  1.0

In [71]:
push!(t3, 3.0)

Set{Int64} with 4 elements:
  6
  2
  9
  3

In [72]:
push!(t3, 4.2)

LoadError: InexactError: Int64(4.2)

In [1]:
N=24
t5=collect(1:N)

24-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24

In [2]:
t4=[i for i in N:-1:1]

24-element Vector{Int64}:
 24
 23
 22
 21
 20
 19
 18
 17
 16
 15
 14
 13
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

In [3]:
append!(t5,t4[2:end])

47-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
  ⋮
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

In [76]:
tmp=[4, 6, 3]

3-element Vector{Int64}:
 4
 6
 3

In [77]:
fill(tmp[1],10)

10-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4

In [78]:
tmp1=repeat(tmp,10)

30-element Vector{Int64}:
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4
 ⋮
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4
 6
 3

In [79]:
append!(tmp1,tmp[1])

31-element Vector{Int64}:
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4
 ⋮
 6
 3
 4
 6
 3
 4
 6
 3
 4
 6
 3
 4

In [80]:
t6=fill(tmp[1],10)
t7=fill(tmp[2],20)
t8=fill(tmp[3],30)
append!(t6,t7)
append!(t6,t8)

60-element Vector{Int64}:
 4
 4
 4
 4
 4
 4
 4
 4
 4
 4
 6
 6
 6
 ⋮
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3
 3

In [81]:
t9=[2^tmp[i] for i in 1:3]

3-element Vector{Int64}:
 16
 64
  8

In [82]:
t10=fill(2^tmp[3],3)
append!(t9,t10)

6-element Vector{Int64}:
 16
 64
  8
  8
  8
  8

In [83]:
a=0
for i in 1:length(t9)
    for j in 0:5
        if div(t9[i],10^j)%10==6
            a=a+1
        end
    end
end
print(a)

2

In [85]:
y=[cos(x)*exp(x) for x in 3:0.1:6]

31-element Vector{Float64}:
 -19.884530844146987
 -22.178753389342127
 -24.490696732801293
 -26.77318244299338
 -28.969237768093574
 -31.011186439374516
 -32.819774760338504
 -34.30336011037369
 -35.35719361853035
 -35.86283371230767
 -35.68773248011913
 -34.68504225166807
 -32.693695428321746
   ⋮
  25.046704998273004
  42.09920106253839
  61.99663027669454
  84.92906736250268
 111.0615860420258
 140.5250750527875
 173.40577640857734
 209.73349424783467
 249.46844055885668
 292.4867067371223
 338.5643778585117
 387.36034029093076

In [88]:
summy=0
for i in 1:length(y)
    summy+=y[i]
end
print("y mean = ", summy/length(y))

y mean = 53.11374594642971

In [89]:
arr311=[[0.1^i 0.2^(i-2)] for i in 3:3:36]

12-element Vector{Matrix{Float64}}:
 [0.0010000000000000002 0.2]
 [1.0000000000000004e-6 0.0016000000000000003]
 [1.0000000000000005e-9 1.2800000000000005e-5]
 [1.0000000000000006e-12 1.0240000000000006e-7]
 [1.0000000000000009e-15 8.192000000000005e-10]
 [1.000000000000001e-18 6.5536000000000055e-12]
 [1.0000000000000012e-21 5.2428800000000056e-14]
 [1.0000000000000014e-24 4.194304000000005e-16]
 [1.0000000000000015e-27 3.3554432000000048e-18]
 [1.0000000000000017e-30 2.684354560000004e-20]
 [1.0000000000000018e-33 2.1474836480000035e-22]
 [1.000000000000002e-36 1.717986918400003e-24]

In [90]:
M=25
arr312=[(2^i)/i for i in 1:M]

25-element Vector{Float64}:
      2.0
      2.0
      2.6666666666666665
      4.0
      6.4
     10.666666666666666
     18.285714285714285
     32.0
     56.888888888888886
    102.4
    186.1818181818182
    341.3333333333333
    630.1538461538462
   1170.2857142857142
   2184.5333333333333
   4096.0
   7710.117647058823
  14563.555555555555
  27594.105263157893
  52428.8
  99864.38095238095
 190650.18181818182
 364722.0869565217
 699050.6666666666
      1.34217728e6

In [113]:
N=30
arr313=["fn"*string(i) for i in 1:N]

30-element Vector{String}:
 "fn1"
 "fn2"
 "fn3"
 "fn4"
 "fn5"
 "fn6"
 "fn7"
 "fn8"
 "fn9"
 "fn10"
 "fn11"
 "fn12"
 "fn13"
 ⋮
 "fn19"
 "fn20"
 "fn21"
 "fn22"
 "fn23"
 "fn24"
 "fn25"
 "fn26"
 "fn27"
 "fn28"
 "fn29"
 "fn30"

In [4]:
N=250
x314=rand(0:999, N)
y314=rand(0:999, N)

250-element Vector{Int64}:
 285
 260
 777
 506
 618
 766
 591
  10
 399
 263
 532
 144
 301
   ⋮
 931
 896
 488
 124
 571
 652
 966
 406
 336
 717
 529
 553

In [5]:
t3141=[y314[i+1]-x314[i] for i in 1:N-1]

249-element Vector{Int64}:
 -191
  -63
  -79
  563
  533
  573
 -483
   58
 -609
  383
 -686
 -164
 -773
    ⋮
  609
  203
 -285
 -686
  518
 -114
  637
 -248
 -546
  234
  244
 -325

In [164]:
t3142=[x314[i]+2*x314[i+1]-x314[i+2] for i in 1:N-2]

248-element Vector{Int64}:
 1126
 1339
 1465
 2518
  253
 1039
 1443
  623
  -92
 1394
  682
  614
   10
    ⋮
  711
 1412
 1403
 1447
 -172
 1487
 2034
  598
  300
 1524
  941
  227

In [165]:
t3143=[sin(y314[i])/cos(x314[i+1]) for i in 1:N-1]

249-element Vector{Float64}:
    4.380285486474569
   -0.6815204438976953
    2.9100592596446186
   -4.503192558366575
    0.7230623961879205
 -156.5782350868654
   23.65045512229104
    1.1145805765484145
    0.9884868255616273
   -1.3362478719992334
    0.16586660815822404
   -0.13095549863225464
    0.9593392937879452
    ⋮
    6.423627927880629
   -2.7153253098841303
   -0.6596325415130156
    1.111822943518316
    1.4465436391552542
   -0.9732449443388187
   -0.05507981687258166
   -0.7627770633858157
    0.897674188002464
   -1.9212613758875194
    1.6994123672757662
    2.5901815629956526

In [166]:
t3144=0
for i in 1:N-1
    t3144+=(exp(-x314[i+1])/(x314[i]+10))
end
t3144

0.0006578070827282885

In [167]:
for i in 1:N
    if y314[i]>600
        println(i, " ", y314[i])
    end
end

5 698
7 847
8 822
10 954
13 801
16 603
17 717
18 706
20 992
23 620
26 870
27 669
30 604
32 695
33 682
39 964
43 652
44 849
47 954
48 951
49 973
52 761
55 818
57 627
58 682
61 727
66 735
69 773
73 796
77 789
79 720
83 820
84 839
85 781
86 730
89 735
93 635
98 607
100 968
102 645
104 655
108 602
110 609
113 644
114 656
115 928
116 669
117 985
118 793
120 667
121 622
124 861
126 667
127 851
129 656
130 689
131 610
132 841
134 746
138 660
139 729
140 815
142 671
143 884
144 956
148 895
149 974
151 749
152 608
153 905
160 917
165 944
167 902
170 666
171 994
173 710
174 906
175 627
176 791
177 669
181 701
182 894
184 628
190 605
191 745
192 926
193 671
194 899
195 780
196 981
198 699
202 922
203 603
204 882
205 892
206 879
207 968
209 617
216 891
221 681
223 873
225 830
226 655
229 857
233 872
235 879
236 699
237 766
239 927
241 909
247 608
248 920
249 714
250 946


In [168]:
for i in 1:N
    if y314[i]>600
        println(x314[i])
    end
end

872
721
454
203
356
398
485
603
805
758
597
882
967
404
554
158
736
858
513
469
468
235
690
926
698
788
24
274
784
555
118
184
265
479
9
998
964
119
598
803
10
288
106
241
247
643
65
883
798
857
521
722
326
66
329
565
989
501
273
540
179
554
54
796
397
750
919
171
100
306
390
804
421
530
598
74
968
680
240
720
2
341
877
678
822
809
631
404
573
243
762
23
839
69
573
35
385
897
612
74
731
6
40
197
196
334
227
709
790
515
703
288
338
737


In [169]:
using Statistics
t3147=[sqrt(abs(x314[i]-mean(x314))) for i in 1:N]

250-element Vector{Float64}:
 16.48199017109281
 16.892128344291017
 13.503481032681906
 17.898156329633508
 19.166220284657065
 21.299201862980688
 14.708636918491122
  7.117302859932265
 17.850938350686217
 17.368246889078932
 13.391937873213122
 18.101270673629518
 12.192456684360211
  ⋮
 16.892128344291017
  7.703505695460995
  3.21620894843603
 18.911795261159106
 21.825306412511143
 10.832543560955571
 17.710335965192755
  9.932572677811121
 14.08346548261471
 14.71923911076928
 12.909531362524358
 15.242834382095738

In [170]:
t3148=0
maxy314=0
for i in 1:N
    if y314[i]>maxy314
        maxy314=y314[i]
    end
end
for i in 1:N
    if maxy314-y314[i]<=200
        t3148+=1
    end
end
t3148

51

In [171]:
xch=0
xnch=0
for i in 1:N
    if x314[i]%2==0
        xch+=1
    else
        xnch+=1
    end
end
print(xch, " ", xnch)    

124 126

In [172]:
t31410=0
for i in 1:N
    if x314[i]%7==0
        t31410+=1
    end
end
print(t31410)

32

In [176]:
#y314=rand(0:999, 250)
a=collect(1:250)
check=0
for i in 1:N
    for j in 1:N-i
        if y314[j]>y314[j+1]
            check=y314[j]
            y314[j]=y314[j+1]
            y314[j+1]=check
            check=a[j]
            a[j]=a[j+1]
            a[j+1]=check
        end
    end
end
t31411=[]
for i in 1:N
    append!(t31411, x314[a[i]])
end
t31411

250-element Vector{Any}:
 233
 790
 687
 825
 872
  51
 721
 454
 186
 203
 684
 177
 356
   ⋮
 790
 564
 515
 147
 981
 622
 191
 406
 703
 288
 338
 737

In [179]:
t31412=sort(x314)
print(t31412[241:250])

[949, 952, 956, 964, 967, 968, 977, 981, 989, 998]

In [183]:
t31413=[t31412[1]]
for i in 1:N
    if t31412[i]!=t31413[end]
        append!(t31413, t31412[i])
    end
end
t31413

217-element Vector{Int64}:
   1
   2
   6
   9
  10
  14
  23
  24
  35
  39
  40
  43
  45
   ⋮
 928
 944
 949
 952
 956
 964
 967
 968
 977
 981
 989
 998

In [184]:
squares=[i^2 for i in 1:100]

100-element Vector{Int64}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [188]:
using Primes

In [191]:
t5=[prime(i) for i in 1:168]
println(t5)
println(t5[89])
t51=t5[89:99]
print(t51)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
461
[461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523]

In [194]:
t61=0
for i in 10:100
    t61+=i^3+4*i^2
end
print(t61)

26852735

In [198]:
t62=0
M=25
for i in 1:M
    t62+= 2^i/i + 3^i/i^2
end
print(t62)

2.1291704368143802e9

In [199]:
t63=1
check=1
for i in 1:19
    check*=2*i/(2*i+1)
    t63+=check
end
print(t63)

6.976346137897618